#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 24 15:56:06 +07 2024
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -view /home/quocna/project/uvm_fifo/uvm_fifo/top_behav.wcfg -log simulate.log"
xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -view /home/quocna/project/uvm_fifo/uvm_fifo/top_behav.wcfg -log simulate.log

